version: 1

formatters:
    simple:
        format: "%(name)s - %(lineno)d -  %(message)s"


handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple


loggers:

    __main__:
        level: INFO
        handlers: [console]
        propagate: yes
        
    draid.graph_wrapper:
        level: DEBUG
        propagate: yes

    draid.prolog_handle:
        level: DEBUG
        propagate: yes

    draid.reason:
        level: DEBUG
        propagate: yes

    draid.recognizer:
        level: DEBUG
        propagate: yes

    draid.rule_database_helper:
        level: DEBUG
        propagate: yes

    draid.sparql_helper:
        level: WARNING
        propagate: yes

    draid.visualise:
        level: DEBUG
        propagate: yes
