version: 1

formatters:
    simple:
        format: "%(name)s - %(lineno)d -  %(message)s"


handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple


loggers:

    __main__:
        level: INFO
        handlers: [console]
        propagate: yes
        
    exp.graph_wrapper:
        level: DEBUG
        propagate: yes

    exp.prolog_handle:
        level: DEBUG
        propagate: yes

    exp.reason:
        level: DEBUG
        propagate: yes

    exp.recognizer:
        level: WARNING
        propagate: yes

    exp.sparql_helper:
        level: WARNING
        propagate: yes

    exp.visualise:
        level: DEBUG
        propagate: yes
